### ISSUE TITLE
Chart museum events / notifications

### ISSUE THREAD

**Issue by ysaakpr** [helm/chartmuseum#493] opened 2021-10-09 15:04 UTC
Are there anyway to get an event to or webhook trigger, whenever there is a push happened to the hosted chartmuseum.

This will help us to send a notifications to user about a new version of chart pushed to the repo..

Are there any options available in chartmuseum for this.

**Comment by scbizu** [comment] 2021-11-06 08:57
Duplicate of #83

**Closed by scbizu** 2021-11-06 08:57 UTC
