### ISSUE TITLE
Running 0.13.1 crashing every 10 hours

### ISSUE THREAD

**Issue by EugenMayer** [helm/chartmuseum#501] opened 2021-11-12 09:29 UTC
Crashing every 10 ours when running 0.13.1

- local storage
- basic auth enabled
- very few clients, 10 requests a day
- 3GB RAM (2.5 free, soo oom is unlikely)

```
docker --version
Docker version 20.10.10, build b485636
```

kerne 5.10.70-1 (debian bullseye)

Apparently, there are no logs why it is crashing. I see client access and then the server is just dead. Exit code is 255

**Comment by cbuto** [comment] 2022-03-01 16:14
@EugenMayer are you still having issues with this?

**Comment by EugenMayer** [comment] 2022-03-01 20:59
It was happening for weeks, several, and then it stopped suddenly. At least for what is See know, it is running for a fair while. Assuming the following reasons :

- docker mtu issues. Since we are running a MTU of 1345 but did not configure this at on the docker-compose level, it could cause unpredictable issues
- DNS issues, we had a fresh internal DNS server which we worked on a couple of times.

So for me the issue is fixed and since it is 4 months in the past, I cannot provide any real informations any longer

**Comment by cbuto** [comment] 2022-03-01 22:29
gotcha thanks for the info! Since its seems like it might have been caused by something external to ChartMuseum (and I haven't seen any other issues come up), I'm going to close this one out.

**Closed by cbuto** 2022-03-01 22:29 UTC
