### ISSUE TITLE
Chart package can not be uploaded to the chartmuseum

### ISSUE THREAD

**Issue by chenlein** [helm/chartmuseum#195] opened 2018-12-21 09:16 UTC
The helm information:
```shell
[root@master-0 charts]# helm version
Client: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.0", GitCommit:"d325d2a9c179b33af1a024cdb5a4472b6288016a", GitTreeState:"clean"}

[root@master-0 charts]# curl -k https://chartmuseum.kube.sz/health
{"healthy":true}

[root@master-0 charts]# curl -k https://chartmuseum.kube.sz/api/charts
{}

[root@master-0 charts]# helm repo list
NAME  	URL                                             
stable	https://kubernetes-charts.storage.googleapis.com
local 	http://127.0.0.1:8879/charts                    
museum	https://chartmuseum.kube.sz  
```

The error message：
```shell
[root@master-0 charts]# curl --data-binary "./chartmuseum-1.8.0.tgz" https://chartmuseum.kube.sz/api/charts -kv
* About to connect() to chartmuseum.kube.sz port 443 (#0)
*   Trying 192.168.114.230...
* Connected to chartmuseum.kube.sz (192.168.114.230) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=ChartMuseum,OU=YPT,O=DM,L=WH,ST=HB,C=CN
* 	start date: 12月 21 07:48:15 2018 GMT
* 	expire date: 12月 18 07:48:15 2028 GMT
* 	common name: ChartMuseum
* 	issuer: OU=YPT,O=DM,L=WH,ST=HB,C=CN
> POST /api/charts HTTP/1.1
> User-Agent: curl/7.29.0
> Host: chartmuseum.kube.sz
> Accept: */*
> Content-Length: 23
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 23 out of 23 bytes
< HTTP/1.1 500 Internal Server Error
< Server: nginx/1.15.6
< Date: Fri, 21 Dec 2018 09:13:02 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 32
< Connection: keep-alive
< X-Request-Id: 01c879aacff4bb614aa00b92768571f6
< Strict-Transport-Security: max-age=15724800; includeSubDomains
< 
* Connection #0 to host chartmuseum.kube.sz left intact
{"error":"gzip: invalid header"}

[root@master-0 charts]# helm push chartmuseum-1.8.0.tgz museum --ca-file /etc/docker/certs.d/registry.kube.sz/ca.crt 
Pushing chartmuseum-1.8.0.tgz to museum...
Error: 500: open /storage/chartmuseum-1.8.0.tgz: permission denied
Error: plugin "push" exited with error
```
Thanks for you help!

**Comment by jdolitsky** [comment] 2018-12-21 16:35
@chenlein the issue is in the curl command, you need to use the `@` symbol

Instead of 
```
curl --data-binary "./chartmuseum-1.8.0.tgz" https://chartmuseum.kube.sz/api/charts -kv
```

Use
```
curl --data-binary "@chartmuseum-1.8.0.tgz" https://chartmuseum.kube.sz/api/charts -kv
```

The string "./chartmuseum-1.8.0.tgz" is being uploaded vs the package itself. You may also want to take a look at the [helm-push](https://github.com/chartmuseum/helm-push) plugin.

**Comment by jdolitsky** [comment] 2018-12-21 16:39
@chenlein In terms of the 500/permission denied from helm push, this looks like you're experiencing #193. Which version of the chart are you using? This has been fixed in chart version 1.8.2

**Closed** 2018-12-24 00:40 UTC

**Comment by pjain17** [comment] 2019-06-04 18:31
Having the same issue with chart-version : 2.3.1, app-version : 0.8.2
```
curl http://localhost:8081/health
{"healthy":true}

curl -L --data-binary "@frame-face-redis-docker-compose-0.0.1.tgz" http://localhost:8081/api/charts
{"error":"open /storage/frame-face-redis-docker-compose-0.0.1.tgz: permission denied"}
```
```
$kubectl exec -it harmonious-stocking-chartmuseum-d87b65cf9-kmlp6 -- /bin/sh
/ $ ls -l
drwxr-xr-x    2 root     root          4096 Jun  3 22:39 storage
/ $ id
uid=1000(chartmuseum) gid=1000(chartmuseum) groups=1000(chartmuseum)
```

**Comment by usersina** [comment] 2022-05-21 18:04
I was confused for a second since I built the package in `./output/my-package-0.1.0.tgz`. For curl to work, simply change `./` to `@` so that it becomes `@output/my-package-0.1.0.tgz`

Upload example from my gitlab-ci pipeline for anyone that stumbles on this.
```bash
  script:
    - *get-package-values
    - echo "Uploading the chart ${PACKAGE_NAME}-${PACKAGE_VERSION}.tgz"
    - curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@output/${PACKAGE_NAME}-${PACKAGE_VERSION}.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"
```
